export const START_TIMER = 'START_TIMER';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const STOP_TIMER = 'STOP_TIMER';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
export const SAVE_NEW_PROJECT_START = 'SAVE_NEW_PROJECT_START';
export const SAVE_NEW_PROJECT_SUCCESS = 'SAVE_NEW_PROJECT_SUCCESS';
export const SAVE_NEW_PROJECT_FAILED = 'SAVE_NEW_PROJECT_FAILED';
