export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const SAVE_NEW_TASK_START = 'SAVE_NEW_TASK_START';
export const SAVE_NEW_TASK_SUCCESS = 'SAVE_NEW_TASK_SUCCESS';
export const SAVE_NEW_TASK_FAILED = 'SAVE_NEW_TASK_FAILED';
export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const SAVE_NEW_PROJECT_START = 'SAVE_NEW_PROJECT_START';
export const SAVE_NEW_PROJECT_SUCCESS = 'SAVE_NEW_PROJECT_SUCCESS';
export const SAVE_NEW_PROJECT_FAILED = 'SAVE_NEW_PROJECT_FAILED';
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';
